---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-data
  namespace: logging
  labels:
    component: elasticsearch
    role: data
spec:
  serviceName: elasticsearch-logging
  replicas: 2
  selector:
    matchLabels:
      component: elasticsearch
      role: data
  template:
    metadata:
      labels:
        component: elasticsearch
        role: data
    spec:
      initContainers:
        - name: init-sysctl
          image: busybox:1.27.2
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          securityContext:
            privileged: true
      containers:
        - name: es-data
          image: russellsherman/elasticsearch:6.6.0
          resources:
            limits:
              cpu: 2
            requests:
              cpu: 1
          ports:
            - containerPort: 9300
              name: transport
            - containerPort: 9200
              name: http
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CLUSTER_NAME
              value: myesdb
            - name: NODE_MASTER
              value: "false"
            - name: NODE_INGEST
              value: "false"
            - name: NODE_DATA
              value: "true"
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: PROCESSORS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
          #- name: "ES_PLUGINS_INSTALL"
          #  value: "x-pack"
          livenessProbe:
            tcpSocket:
              port: transport
            initialDelaySeconds: 360
            periodSeconds: 30
          volumeMounts:
            - name: config
              mountPath: /elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
            - name: elasticsearch-data
              mountPath: /data
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: component
                      operator: In
                      values:
                        - elasticsearch
                    - key: role
                      operator: In
                      values:
                        - data
                topologyKey: kubernetes.io/hostname
      volumes:
        - name: config
          configMap:
            name: es-configmap
  volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
