---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-data-discovery
  namespace: logging
  labels:
    component: elasticsearch
    role: data
spec:
  selector:
    component: elasticsearch
    role: data
  ports:
  - port: 9300
    name: transport
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-data-api
  namespace: logging
  labels:
    component: elasticsearch
    role: data
spec:
  selector:
    component: elasticsearch
    role: data
  ports:
  - name: http
    port: 9200
  type: NodePort