---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-ingest
  namespace: logging
  labels:
    component: elasticsearch
    role: ingest
spec:
  selector:
    matchLabels:
      component: elasticsearch
      role: ingest
  serviceName: elasticsearch-ingest
  replicas: 1
  template:
    metadata:
      labels:
        component: elasticsearch
        role: ingest
    spec:
      initContainers:
        - name: init-sysctl
          image: busybox:1.27.2
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          securityContext:
            privileged: true
      containers:
        - name: es-ingest
          image: russellsherman/elasticsearch:6.6.0
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CLUSTER_NAME
              value: myesdb
            - name: NODE_MASTER
              value: "false"
            - name: NODE_INGEST
              value: "true"
            - name: NODE_DATA
              value: "false"
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: NETWORK_HOST
              value: _site_,_lo_
            - name: PROCESSORS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
          resources:
            requests:
              cpu: 1
            limits:
              cpu: 2
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: transport
          livenessProbe:
            httpGet:
              path: /_cluster/health
              port: 9200
            initialDelaySeconds: 120
            timeoutSeconds: 60
          volumeMounts:
            - name: elasticsearch-ingest
              mountPath: /data
            - name: config
              mountPath: /elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
      volumes:
        - name: config
          configMap:
            name: es-configmap
  volumeClaimTemplates:
    - metadata:
        name: elasticsearch-ingest
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 5Gi
