#!/usr/bin/env bash

if [ -z "${KUBECONFIG}" ]; then
    export KUBECONFIG=~/.kube/config
fi

# CAUTION - setting NAMESPACE will deploy most components to the given namespace
# however some are hardcoded to 'monitoring'. Only use if you have reviewed all manifests.

if [ -z "${NAMESPACE}" ]; then
    NAMESPACE=logging
fi

kctl() {
    kubectl --namespace "$NAMESPACE" "$@"
}

# Delete Fluentd
kctl delete -f fluentd-configmap.yaml
kctl delete -f fluentd-daemonset.yaml

# Delete Kibana
kctl delete -f kibana-configmap.yaml
kctl delete -f kibana-external-ingress.yaml
kctl delete -f kibana-svc.yaml
kctl delete -f kibana.yaml

# Delete Curator
kctl delete -f es-curator-configmap.yaml
kctl delete -f es-curator-cronjob.yaml

# Delete Elasticsearch nodes
kctl delete -f es-master-statefulset.yaml
kctl delete -f es-ingest-statefulset.yaml
kctl delete -f es-data-statefulset.yaml

# Delete Elasticsearch services
kctl delete -f es-ingest-svc.yaml
kctl delete -f es-master-svc.yaml
kctl delete -f es-data-svc.yaml

# Delete Cerebro
kctl delete -f cerebro.yaml
kctl delete -f cerebro-external-ingress.yaml

# Delete namespace
kubectl delete namespace $NAMESPACE

echo "done!"

